<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__a-vncl9jrku60c</name>
   <tag></tag>
   <elementGuidId>9464b92b-c287-4a71-b56b-4c44e4183284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-vncl9jrku60c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-vncl9jrku60c&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7bdcd9c0-7e00-4cc4-9dc8-f3da020600a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>aa3b31fb-0485-40f4-877c-2abf0f2d7fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcHCOgUAAAAAH9xUAJ4hGUMzWx6IG78K6WJmDvL&amp;co=aHR0cHM6Ly90cGRjYXMuaXBzdC5hYy50aDo0NDM.&amp;hl=th&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;size=normal&amp;cb=b9hrcpwj24ns</value>
      <webElementGuid>8e1a26eb-eab2-432b-afd2-59bf4dbc9753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>ca85670a-c722-4e3c-ab19-fc2195dc8fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>69a3bd1c-c2cc-4d2c-ba08-11ffa6113425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7a122fe1-74c6-488e-8746-46fec34f1ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-vncl9jrku60c</value>
      <webElementGuid>42227bae-d6d7-4fef-840a-3816fc2f3fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43c9f7ae-e978-4c8b-90c8-ef07794a6734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>befba625-4f88-40fc-ad22-8f4fe1b4d6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>fa32c2b4-8e9f-4de3-a395-71ea2340d837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-register-form&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-12 col-lg-12&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>fb4db6ae-88bc-4bb2-8489-e42a3843f52e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-vncl9jrku60c']</value>
      <webElementGuid>1c8df8bb-c3c8-4135-a1b3-f7240c0c9e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-register-form']/div[17]/div/div/div/div/iframe</value>
      <webElementGuid>42d11a16-226b-45b5-8929-85074de79c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>12810abd-fb9e-4942-9153-1cd45f9c1ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcHCOgUAAAAAH9xUAJ4hGUMzWx6IG78K6WJmDvL&amp;co=aHR0cHM6Ly90cGRjYXMuaXBzdC5hYy50aDo0NDM.&amp;hl=th&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;size=normal&amp;cb=b9hrcpwj24ns' and @name = 'a-vncl9jrku60c']</value>
      <webElementGuid>76e8d851-795d-4354-a52f-140d4a606752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
