<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(htmlclass, , login-pf, , body_53ae63</name>
   <tag></tag>
   <elementGuidId>857713c0-2e69-4b2d-adb7-fab0cd342f4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-vncl9jrku60c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-vncl9jrku60c&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9e62fbcf-ef77-4b2b-b2ca-fb91642c6212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>รหัส reCAPTCHA จะหมดอายุใน 2 นาที</value>
      <webElementGuid>57a57b12-20e7-4b61-8f11-07485805e89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=th&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;k=6LcHCOgUAAAAAH9xUAJ4hGUMzWx6IG78K6WJmDvL</value>
      <webElementGuid>bd262824-0532-4432-95ad-db04156da281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-vncl9jrku60c</value>
      <webElementGuid>1870b965-4852-454b-96ab-7ed01dedba5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9add7960-9b26-4c6a-bd3d-ad7da228e347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cbd89309-2403-4bb8-9d7a-064020de72db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>918e56da-1d61-4f76-ba02-4aedeb9adde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;login-pf&quot;]/body[1]/div[3]/div[4]/iframe[1]</value>
      <webElementGuid>9d0cc2f3-37d3-4827-8a89-7e9e4b028a09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-vncl9jrku60c']</value>
      <webElementGuid>cfcd5db8-d3fe-416c-85ce-b216cd6e38bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>62b2b35d-1c69-44cc-b54b-02c1526d0120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'รหัส reCAPTCHA จะหมดอายุใน 2 นาที' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=th&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;k=6LcHCOgUAAAAAH9xUAJ4hGUMzWx6IG78K6WJmDvL' and @name = 'c-vncl9jrku60c']</value>
      <webElementGuid>df73ad27-0fe2-48f5-bd1e-9cab5422fc68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
