<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>566b19da-cf33-41ca-a510-5a8d5b009d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8d2a4bb-e0bd-4061-bae8-267e74060ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>19aa40ac-74e3-4e3e-8b6f-9826701417b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AKH6MRHT2e8sG4YT9ij2rcokdPzxYVy5C3UcuPBJgSr17Hh3RONljyWrHcE0dKmWBUlaH_93xHfMgYRNsxWg0JiTM3nA0xKMIF2Jxjeb5xhtU2b5JkOxVwU4EOdNTxxfp_q7JbQ31Ezmp0LHj__lRT470hCWnRsYxpzZGVruCgx3ej4i9nDm6iuqD80onWGQDBVoIef5pKRbLkXBx2GF2AflmCbG8VLef7BtG_jBPHX4Cz9YfvS4dg4&amp;k=6LcHCOgUAAAAAH9xUAJ4hGUMzWx6IG78K6WJmDvL</value>
      <webElementGuid>113bfed6-2bac-40fb-8a11-d0a4732d8584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>d7a0d2a1-17e3-4559-94cb-792b3f1533c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_IPST/iframe_concat(htmlclass, , login-pf, , body_53ae63</value>
      <webElementGuid>b1dc6a3b-4520-4250-87bf-82ed522505db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>83116bc4-b59f-42b7-88e6-303e12fb4296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AKH6MRHT2e8sG4YT9ij2rcokdPzxYVy5C3UcuPBJgSr17Hh3RONljyWrHcE0dKmWBUlaH_93xHfMgYRNsxWg0JiTM3nA0xKMIF2Jxjeb5xhtU2b5JkOxVwU4EOdNTxxfp_q7JbQ31Ezmp0LHj__lRT470hCWnRsYxpzZGVruCgx3ej4i9nDm6iuqD80onWGQDBVoIef5pKRbLkXBx2GF2AflmCbG8VLef7BtG_jBPHX4Cz9YfvS4dg4&amp;k=6LcHCOgUAAAAAH9xUAJ4hGUMzWx6IG78K6WJmDvL')])[9]</value>
      <webElementGuid>75a09e27-9aca-4dde-a0f7-4c6d26136811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>7d27e214-af8e-4333-9436-8b60044322af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AKH6MRHT2e8sG4YT9ij2rcokdPzxYVy5C3UcuPBJgSr17Hh3RONljyWrHcE0dKmWBUlaH_93xHfMgYRNsxWg0JiTM3nA0xKMIF2Jxjeb5xhtU2b5JkOxVwU4EOdNTxxfp_q7JbQ31Ezmp0LHj__lRT470hCWnRsYxpzZGVruCgx3ej4i9nDm6iuqD80onWGQDBVoIef5pKRbLkXBx2GF2AflmCbG8VLef7BtG_jBPHX4Cz9YfvS4dg4&amp;k=6LcHCOgUAAAAAH9xUAJ4hGUMzWx6IG78K6WJmDvL']</value>
      <webElementGuid>cd4a9855-8cd6-4742-8fde-bb229ecea0a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
