<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirmEmail</name>
   <tag></tag>
   <elementGuidId>5eea0582-5e90-490e-8258-9ab28d5dca41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>803f1b7b-c0c2-405d-a7cc-a4ede8843bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>c3b70f91-172a-49a0-829e-7fb00fd9dee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>f1fd0f3e-5233-43f1-ab49-f6cfd675c63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-error</value>
      <webElementGuid>8e2cc935-af5a-4599-b47f-dfeeda479289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>56552429-7c36-4b36-858b-145417ab4927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>กรุณากรอกอีเมลยืนยันให้ตรงกัน</value>
      <webElementGuid>14aa9006-e026-4254-840f-bea0f813fbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmEmail&quot;)</value>
      <webElementGuid>f246002f-2c24-4035-924e-7c1f189b79c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmEmail']</value>
      <webElementGuid>20ddd294-49be-4629-9cd3-101a4d731933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-register-form']/div[13]/div[2]/input</value>
      <webElementGuid>ee415ffc-e64b-4aef-a791-d6f3476e646e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/input</value>
      <webElementGuid>5f2e64d3-61e7-42a5-a19c-0b8e1e5d366c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'confirmEmail' and @id = 'confirmEmail' and @name = 'confirmEmail' and @title = 'กรุณากรอกอีเมลยืนยันให้ตรงกัน']</value>
      <webElementGuid>0e7c3dfc-6e52-4c92-9834-b88f411a03ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
