<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirmEmail_1</name>
   <tag></tag>
   <elementGuidId>b5ff8ec1-abb0-4262-937f-529035ba63af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a61b9208-e153-4d8f-a7c2-5aeee301ec1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>1fc20cc7-a078-4784-9b9d-fb9111a772d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>22ad6afe-ba62-4af7-bf98-4aff91ce37c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-error</value>
      <webElementGuid>437deacb-be42-4e9a-b72f-619e10c7a770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>b5a6d8f0-313b-42cc-9d85-4c69b1e3c606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>กรุณากรอกยืนยันอีเมลให้ถูกต้อง</value>
      <webElementGuid>a4a75e22-7125-4ec0-9742-1a5b97fc83b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>tossapon@gmail.com</value>
      <webElementGuid>a93a2d69-29b0-4491-ad12-8dffeacaa7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmEmail&quot;)</value>
      <webElementGuid>13087736-524c-4d9c-95a3-2d64803827fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmEmail']</value>
      <webElementGuid>c36a7f48-b0a9-4357-9319-2bda06adf1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-register-form']/div[13]/div[2]/input</value>
      <webElementGuid>ac4f732e-7076-49b3-96dd-348b37ce2ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/input</value>
      <webElementGuid>6e43dc73-a4cc-4fa2-99b3-456f7cf3be20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'confirmEmail' and @id = 'confirmEmail' and @name = 'confirmEmail' and @title = 'กรุณากรอกยืนยันอีเมลให้ถูกต้อง']</value>
      <webElementGuid>54022fa6-2ddd-4fe3-8637-4e09c6cc1ea1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
