<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__password</name>
   <tag></tag>
   <elementGuidId>98fcdb45-4f8a-4ba4-be84-7aa2f2d111f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5351c61-6494-444f-9194-068e35c6ad77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7f528e4c-c81e-4b62-8521-2193ff5aa821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>817fcafe-e2f1-477a-87d9-bf2d07e09c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate-password form-error</value>
      <webElementGuid>0a3a50d6-375e-4e0e-a0b3-3f7d7a41ebe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f6a3e955-42c3-4953-b5d3-a22d46f70d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>5799a13b-49f6-4492-8d33-e2e75afad0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}$</value>
      <webElementGuid>2775923f-ca32-4afc-a9c1-ba04ebfe9188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>รหัสผ่านต้องมีความยาวอย่างน้อย 6 ตัวอักษร โดยจะต้องประกอบด้วยตัวอักษรภาษาอังกฤษและตัวเลขเท่านั้น</value>
      <webElementGuid>226048e9-d002-4b35-ae0b-c081f74d5e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password&quot;)</value>
      <webElementGuid>a9c8937c-ae50-4df2-bfef-79425c892d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password']</value>
      <webElementGuid>b6430503-04be-4591-9d4b-cacafd61b02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-register-form']/div[15]/div[2]/input</value>
      <webElementGuid>d489f489-e008-4f54-9e24-ca9afb407904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/input</value>
      <webElementGuid>f5f562a1-bb3e-4154-a161-9564fa4634cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'password' and @name = 'password' and @title = 'รหัสผ่านต้องมีความยาวอย่างน้อย 6 ตัวอักษร โดยจะต้องประกอบด้วยตัวอักษรภาษาอังกฤษและตัวเลขเท่านั้น']</value>
      <webElementGuid>1d115b99-0cb8-4f23-b0ac-256c0d3e3b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
