<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__username</name>
   <tag></tag>
   <elementGuidId>918b60b2-91e8-4316-9b4b-51f348015216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>724a3da6-3b01-4052-9154-929a9e80f9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eed9d4c6-f9b3-4538-9029-6b44ee69fe8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>ebe6163c-514e-437e-8287-2d4fe085d15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-error</value>
      <webElementGuid>1dc5e258-5331-4788-be65-b3bf072ecefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>00ea2624-b8c8-44f5-870a-7415ccede359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>110af2a2-0e49-422c-890c-a208d717b397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-z]{1}[a-z0-9]{3,19}</value>
      <webElementGuid>8506aa91-19c2-4f2c-aef9-77e610124a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ชื่อผู้ใช้ต้องมีความยาวอย่างน้อย 4 ตัวอักษร แต่ไม่เกิน 20 ตัวอักษร ตัวแรกต้องเป็นอักษรภาษาอังกฤษ ตามด้วยตัวอักษรภาษาอังกฤษหรือตัวเลขเท่านั้น</value>
      <webElementGuid>dd366c49-76ca-4a42-bc66-0dcc56ed3aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username&quot;)</value>
      <webElementGuid>803f8bf2-330a-40a8-a2f1-a2005ed79a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username']</value>
      <webElementGuid>9697d58d-6f46-4ba7-a8b6-fa4fca470c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-register-form']/div[14]/div[2]/input</value>
      <webElementGuid>1aad0ee4-2195-4820-b18a-c03d3e65957f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/input</value>
      <webElementGuid>d27dd9ff-84b5-4ffe-9371-09c8a2ffc8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'username' and @name = 'username' and @title = 'ชื่อผู้ใช้ต้องมีความยาวอย่างน้อย 4 ตัวอักษร แต่ไม่เกิน 20 ตัวอักษร ตัวแรกต้องเป็นอักษรภาษาอังกฤษ ตามด้วยตัวอักษรภาษาอังกฤษหรือตัวเลขเท่านั้น']</value>
      <webElementGuid>0d703e1b-b11a-4f68-844d-725d3dd5e235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
