<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user.attributes.RawPersonId</name>
   <tag></tag>
   <elementGuidId>9ad741be-a88d-4d80-b2f3-e9b484f54f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PersonIdInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PersonIdInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9157f16f-3ab1-4097-bdf5-c466991a3bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>486de673-8d9e-4c67-8b27-779ead22bf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PersonIdInput</value>
      <webElementGuid>8cc3b1b6-a5d1-496e-8411-6bd473ec0574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user.attributes.RawPersonId</value>
      <webElementGuid>e9d65fb1-ea4c-48ee-88f4-b29b2d8c71ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-tooltip form-error</value>
      <webElementGuid>ffeca1e5-6ebf-4fbd-98f3-70f6cb7f257b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{13}</value>
      <webElementGuid>20773a0d-d724-420d-a0cb-f16ddcbb40d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>หมายเลขบัตรประชาชน 13 หลัก</value>
      <webElementGuid>67a485ef-f467-4e13-a064-09ccbdf4ded0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PersonIdInput&quot;)</value>
      <webElementGuid>17a0f65a-8d03-48e5-8737-152218ba3db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PersonIdInput']</value>
      <webElementGuid>7820c002-4c9c-422e-9fb2-6bf2d6f44bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-register-form']/div[5]/div[2]/input</value>
      <webElementGuid>ebb90289-6475-42c4-8bd5-e46719509426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>aa6a0ca0-fdfc-47c2-b33d-c6088f5b08fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PersonIdInput' and @name = 'user.attributes.RawPersonId' and @title = 'หมายเลขบัตรประชาชน 13 หลัก']</value>
      <webElementGuid>7fd0a789-d7ec-46d7-89e6-a37197db4b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
