<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user.attributes.Telephone</name>
   <tag></tag>
   <elementGuidId>bb561e2f-561c-484e-b685-6960a2f00ad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user.attributes.Telephone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a28dbbb-cf5d-40d1-b097-e8e868d6b35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c2e0792-2445-4c51-b8bd-bf0a54ef94f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user.attributes.Telephone</value>
      <webElementGuid>65756738-d793-453f-89ef-1a7436a70150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-error</value>
      <webElementGuid>dce99eeb-cebb-4be5-99ac-eb37180e5a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user.attributes.Telephone</value>
      <webElementGuid>bd0270d8-84c3-467f-a327-4ddc04e830ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{10}</value>
      <webElementGuid>0a80186a-4641-4fe4-a46c-d51bf79bcb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>เบอร์โทรศัพท์เคลื่อนที่ 10 หลัก</value>
      <webElementGuid>cb841fd0-9b39-4525-a568-b9a1725335a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user.attributes.Telephone&quot;)</value>
      <webElementGuid>f979a7c6-a6e7-48ee-b558-eaea3dc88a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user.attributes.Telephone']</value>
      <webElementGuid>cd02509a-b5cf-4227-85cb-52ab67b9227e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-register-form']/div[7]/div[2]/input</value>
      <webElementGuid>e37c5331-fd06-4bf0-be09-9bbaa0dd42d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>72902be1-feea-466b-b5a6-a55998767c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user.attributes.Telephone' and @name = 'user.attributes.Telephone' and @title = 'เบอร์โทรศัพท์เคลื่อนที่ 10 หลัก']</value>
      <webElementGuid>cf032fd1-ecc1-49da-8894-29cf2291d2b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
