<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>87aedf0d-3433-464b-9b36-4a1fd8bdaf9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.search-home.punsarn-login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24d11982-dd9e-409e-95b1-59613e5538d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary search-home punsarn-login</value>
      <webElementGuid>ff938c07-ec37-4050-80be-d7f1aaea06e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='https://learn.teacherpd.ipst.ac.th/auth/login/common-oauth2-backend/?auth_entry=register'</value>
      <webElementGuid>d4429aff-05e3-4f5f-809e-762dfa1efd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aab125d3-58b7-4b8f-b9af-e17fb7ecbeba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>เข้าสู่ระบบ/สมัครสมาชิก 
								</value>
      <webElementGuid>8192694e-0a50-4baf-ba69-607b8561129c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-navigation&quot;)/ul[@class=&quot;onepress-menu onepress-menu-login visible-lg hidden-xs hidden-md&quot;]/li[1]/button[@class=&quot;btn btn-primary search-home punsarn-login&quot;]</value>
      <webElementGuid>80d2ae45-85ee-4e89-96c7-0d1424d4fc2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>58cb736c-d9e8-4e6e-9c7c-4fb857b1c756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='site-navigation']/ul[2]/li/button</value>
      <webElementGuid>bccbc714-e62b-4987-ab7f-c37f0c6ea512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เข้าสู่ระบบ/สมัครสมาชิก'])[1]/following::button[1]</value>
      <webElementGuid>c782ab60-50ac-478d-b7b7-ccc582cda69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='วิธีใช้งาน'])[1]/following::button[1]</value>
      <webElementGuid>e54494c6-78c6-4b88-8329-7bb646da9ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ระบบอบรมครู'])[2]/preceding::button[1]</value>
      <webElementGuid>ceae0617-b89a-4f3b-970e-094a4bc9482e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ค้นหารายวิชา'])[1]/preceding::button[1]</value>
      <webElementGuid>7999477d-2c96-4e35-953f-4e57726711d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>834716af-0404-4d04-9bc7-969e992191be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'เข้าสู่ระบบ/สมัครสมาชิก 
								' or . = 'เข้าสู่ระบบ/สมัครสมาชิก 
								')]</value>
      <webElementGuid>8db4b084-a76d-4626-99ea-53441da8e5d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
